// Birthday data is separated by fictional characters and voice actors.


export const lovelive_character_birthdays = [
  { month: 1, date: 1, name: "黑泽黛雅", group: "Aqours" },
  { month: 1, date: 13, name: "村野沙耶香", group: "莲之空女学院学园偶像俱乐部" },
  { month: 1, date: 17, name: "小泉花阳", group: "μ's" },
  { month: 1, date: 20, name: "薇恩·玛格丽特", group: "Liella!" },
  { month: 1, date: 23, name: "中须霞", group: "虹咲学园学园偶像同好会" },
  { month: 2, date: 5, name: "艾玛·维尔德", group: "虹咲学园学园偶像同好会" },
  { month: 2, date: 10, name: "松浦果南", group: "Aqours" },
  { month: 2, date: 13, name: "麻布麻衣", group: "人生不易部！" },
  { month: 2, date: 15, name: "钟岚珠", group: "虹咲学园学园偶像同好会" },
  { month: 2, date: 25, name: "岚千砂都", group: "Liella!" },
  { month: 2, date: 28, name: "徒町小铃", group: "莲之空女学院学园偶像俱乐部" },
  { month: 3, date: 1, name: "上原步梦", group: "虹咲学园学园偶像同好会" },
  { month: 3, date: 2, name: "金泽奇迹", group: "人生不易部！" },
  { month: 3, date: 4, name: "国木田花丸", group: "Aqours" },
  { month: 3, date: 15, name: "园田海未", group: "μ's" },
  { month: 4, date: 3, name: "樱坂雫", group: "虹咲学园学园偶像同好会" },
  { month: 4, date: 4, name: "调布乃理子", group: "人生不易部！" },
  { month: 4, date: 10, name: "樱小路希奈子", group: "Liella!" },
  { month: 4, date: 17, name: "渡边曜", group: "Aqours" },
  { month: 4, date: 19, name: "西木野真姬", group: "μ's" },
  { month: 5, date: 1, name: "涩谷香音", group: "Liella!" },
  { month: 5, date: 4, name: "鹿角圣良", group: "Saint Snow" },
  { month: 5, date: 7, name: "山田真绿", group: "人生不易部！" },
  { month: 5, date: 22, name: "日野下花帆", group: "莲之空女学院学园偶像俱乐部" },
  { month: 5, date: 30, name: "宫下爱", group: "虹咲学园学园偶像同好会" },
  { month: 6, date: 9, name: "东条希", group: "μ's" },
  { month: 6, date: 11, name: "驹形花火", group: "人生不易部！" },
  { month: 6, date: 13, name: "小原鞠莉", group: "Aqours" },
  { month: 6, date: 15, name: "乙宗梢", group: "莲之空女学院学园偶像俱乐部" },
  { month: 6, date: 17, name: "若菜四季", group: "Liella!" },
  { month: 6, date: 26, name: "塞拉斯·柳田·利林菲尔德", group: "莲之空女学院学园偶像俱乐部" },
  { month: 6, date: 29, name: "朝香果林", group: "虹咲学园学园偶像同好会" },
  { month: 7, date: 9, name: "五桐玲", group: "人生不易部！" },
  { month: 7, date: 13, name: "津岛善子", group: "Aqours" },
  { month: 7, date: 17, name: "唐可可", group: "Liella!" },
  { month: 7, date: 22, name: "矢泽妮可", group: "μ's" },
  { month: 8, date: 1, name: "高海千歌", group: "Aqours" },
  { month: 8, date: 3, name: "高坂穗乃果", group: "μ's" },
  { month: 8, date: 7, name: "鬼塚夏美", group: "Liella!" },
  { month: 8, date: 8, name: "优木雪菜", group: "虹咲学园学园偶像同好会" },
  { month: 8, date: 11, name: "圣泽悠奈", group: "Sunny Passion" },
  { month: 8, date: 18, name: "高桥波尔卡", group: "人生不易部！" },
  { month: 8, date: 31, name: "大泽瑠璃乃", group: "莲之空女学院学园偶像俱乐部" },
  { month: 9, date: 12, name: "南小鸟", group: "μ's" },
  { month: 9, date: 19, name: "樱内梨子", group: "Aqours" },
  { month: 9, date: 21, name: "黑泽露比", group: "Aqours" },
  { month: 9, date: 22, name: "春宫悠可里", group: "人生不易部！" },
  { month: 9, date: 24, name: "安养寺姬芽", group: "莲之空女学院学园偶像俱乐部" },
  { month: 9, date: 28, name: "平安名堇", group: "Liella!" },
  { month: 10, date: 5, name: "三船栞子", group: "虹咲学园学园偶像同好会" },
  { month: 10, date: 20, name: "百生吟子", group: "莲之空女学院学园偶像俱乐部" },
  { month: 10, date: 21, name: "绚濑绘里", group: "μ's" },
  { month: 10, date: 29, name: "米女芽衣", group: "Liella!" },
  { month: 11, date: 1, name: "星空凛", group: "μ's" },
  { month: 11, date: 11, name: "佐佐木翔音", group: "人生不易部！" },
  { month: 11, date: 13, name: "天王寺璃奈", group: "虹咲学园学园偶像同好会" },
  { month: 11, date: 17, name: "夕雾缀理", group: "莲之空女学院学园偶像俱乐部" },
  { month: 11, date: 24, name: "叶月恋", group: "Liella!" },
  { month: 12, date: 1, name: "桂城泉", group: "莲之空女学院学园偶像俱乐部" },
  { month: 12, date: 2, name: "柊摩央", group: "Sunny Passion" },
  { month: 12, date: 6, name: "米娅·泰勒", group: "虹咲学园学园偶像同好会" },
  { month: 12, date: 12, name: "鹿角理亚", group: "Saint Snow" },
  { month: 12, date: 16, name: "近江彼方", group: "虹咲学园学园偶像同好会" },
  { month: 12, date: 20, name: "藤岛慈", group: "莲之空女学院学园偶像俱乐部" },
  { month: 12, date: 28, name: "鬼塚冬毬", group: "Liella!" },
];

export const lovelive_voice_actor_birthdays = [
  { month: 1, date: 9, name: "Liyuu", group: "Liella!" },
  { month: 1, date: 19, name: "天泽朱音", group: "人生不易部！" },
  { month: 1, date: 23, name: "小户森穗花", group: "人生不易部！" },
  { month: 1, date: 28, name: "野中心菜", group: "莲之空女学院学园偶像俱乐部" },
  { month: 1, date: 28, name: "叶山风花", group: "莲之空女学院学园偶像俱乐部" },
  { month: 1, date: 31, name: "久保田未梦", group: "虹咲学园学园偶像同好会" },
  { month: 2, date: 1, name: "楠田亚衣奈", group: "μ's" },
  { month: 2, date: 5, name: "小宫有纱", group: "Aqours" },
  { month: 2, date: 7, name: "伊波杏树", group: "Aqours" },
  { month: 2, date: 12, name: "田野麻美", group: "Saint Snow" },
  { month: 2, date: 19, name: "降幡爱", group: "Aqours" },
  { month: 2, date: 23, name: "绘森彩", group: "Liella!" },
  { month: 2, date: 27, name: "小泉萌香", group: "虹咲学园学园偶像同好会" },
  { month: 3, date: 5, name: "矢野妃菜喜", group: "虹咲学园学园偶像同好会" },
  { month: 3, date: 8, name: "岬奈子", group: "Liella!" },
  { month: 3, date: 28, name: "吉武千飒", group: "Sunny Passion" },
  { month: 3, date: 31, name: "藤野心", group: "人生不易部！" },
  { month: 4, date: 3, name: "坂仓花", group: "Liella!" },
  { month: 4, date: 13, name: "大熊和奏", group: "Liella!" },
  { month: 4, date: 17, name: "相良茉优", group: "虹咲学园学园偶像同好会" },
  { month: 4, date: 20, name: "进藤天音", group: "莲之空女学院学园偶像俱乐部" },
  { month: 4, date: 25, name: "前田佳织里", group: "虹咲学园学园偶像同好会" },
  { month: 5, date: 2, name: "Pile", group: "μ's" },
  { month: 5, date: 2, name: "大西亚玖璃", group: "虹咲学园学园偶像同好会" },
  { month: 5, date: 15, name: "林鼓子", group: "虹咲学园学园偶像同好会" },
  { month: 5, date: 16, name: "青山渚", group: "Liella!" },
  { month: 5, date: 19, name: "久保百合花", group: "μ's" },
  { month: 5, date: 21, name: "榆井希实", group: "莲之空女学院学园偶像俱乐部" },
  { month: 5, date: 24, name: "内田秀", group: "虹咲学园学园偶像同好会" },
  { month: 5, date: 31, name: "坂野爱羽", group: "人生不易部！" },
  { month: 6, date: 9, name: "结木由奈", group: "Sunny Passion" },
  { month: 6, date: 18, name: "凉之濑葵音", group: "人生不易部！" },
  { month: 6, date: 28, name: "三森铃子", group: "μ's" },
  { month: 7, date: 1, name: "佩顿尚未", group: "Liella!" },
  { month: 7, date: 12, name: "南条爱乃", group: "μ's" },
  { month: 7, date: 18, name: "薮岛朱音", group: "Liella!" },
  { month: 7, date: 23, name: "内田彩", group: "μ's" },
  { month: 7, date: 23, name: "铃木爱奈", group: "Aqours" },
  { month: 8, date: 5, name: "法元明菜", group: "虹咲学园学园偶像同好会" },
  { month: 8, date: 8, name: "逢田梨香子", group: "Aqours" },
  { month: 8, date: 16, name: "齐藤朱夏", group: "Aqours" },
  { month: 8, date: 20, name: "月音粉", group: "莲之空女学院学园偶像俱乐部" },
  { month: 8, date: 28, name: "佐佐木琴子", group: "莲之空女学院学园偶像俱乐部" },
  { month: 9, date: 7, name: "村上奈津实", group: "虹咲学园学园偶像同好会" },
  { month: 9, date: 17, name: "樱井阳菜", group: "莲之空女学院学园偶像俱乐部" },
  { month: 9, date: 19, name: "濑古梨爱", group: "人生不易部！" },
  { month: 9, date: 20, name: "指出毬亚", group: "虹咲学园学园偶像同好会" },
  { month: 9, date: 25, name: "高槻加奈子", group: "Aqours" },
  { month: 9, date: 27, name: "结那", group: "Liella!" },
  { month: 9, date: 30, name: "伊达小百合", group: "Liella!" },
  { month: 10, date: 4, name: "远藤璃菜", group: "人生不易部！" },
  { month: 10, date: 6, name: "田中千惠美", group: "虹咲学园学园偶像同好会" },
  { month: 10, date: 13, name: "奥村优季", group: "人生不易部！" },
  { month: 10, date: 16, name: "鬼头明里", group: "虹咲学园学园偶像同好会" },
  { month: 10, date: 23, name: "小林爱香", group: "Aqours" },
  { month: 10, date: 24, name: "花宫初奈", group: "莲之空女学院学园偶像俱乐部" },
  { month: 10, date: 26, name: "饭田里穗", group: "μ's" },
  { month: 11, date: 1, name: "铃原希实", group: "Liella!" },
  { month: 11, date: 2, name: "诹访奈奈香", group: "Aqours" },
  { month: 11, date: 8, name: "来栖凛", group: "莲之空女学院学园偶像俱乐部" },
  { month: 11, date: 19, name: "菅叶和", group: "莲之空女学院学园偶像俱乐部" },
  { month: 12, date: 10, name: "新田惠海", group: "μ's" },
  { month: 12, date: 14, name: "三宅美羽", group: "莲之空女学院学园偶像俱乐部" },
  { month: 12, date: 22, name: "楠木灯", group: "虹咲学园学园偶像同好会" },
  { month: 12, date: 23, name: "佐藤日向", group: "Saint Snow" },
  { month: 12, date: 26, name: "德井青空", group: "μ's" },
  { month: 12, date: 31, name: "绫咲穗音", group: "人生不易部！" },
];

// Character data is based on the official BanG Dream! character profiles.

export const bangdream_character_birthdays = [
  { month: 1, date: 7, name: "羽泽鸫", group: "Afterglow" },
  { month: 1, date: 13, name: "和奏瑞依(LAYER)", group: "RAISE A SUILEN" },
  { month: 1, date: 14, name: "若叶睦", group: "Ave Mujica" },
  { month: 2, date: 7, name: "峰月律", group: "梦限大 MewType" },
  { month: 2, date: 14, name: "丰川祥子", group: "Ave Mujica" },
  { month: 2, date: 19, name: "仓田真白", group: "Morfonica" },
  { month: 2, date: 22, name: "要乐奈", group: "MyGO!!!!!" },
  { month: 2, date: 28, name: "濑田薰", group: "Hello, Happy World!" },
  { month: 3, date: 5, name: "四宫宁月", group: "一家 Dumb Rock!" },
  { month: 3, date: 12, name: "汐见萤", group: "millsage" },
  { month: 3, date: 20, name: "冰川日菜", group: "Pastel＊Palettes" },
  { month: 3, date: 20, name: "冰川纱夜", group: "Roselia" },
  { month: 3, date: 23, name: "牛込里美", group: "Poppin'Party" },
  { month: 3, date: 25, name: "鳰原令王那(PAREO)", group: "RAISE A SUILEN" },
  { month: 3, date: 30, name: "伊泽枣", group: "millsage" },
  { month: 4, date: 2, name: "梅里千樱梨", group: "一家 Dumb Rock!" },
  { month: 4, date: 6, name: "白鹭千圣", group: "Pastel＊Palettes" },
  { month: 4, date: 7, name: "八幡海铃", group: "Ave Mujica" },
  { month: 4, date: 10, name: "美竹兰", group: "Afterglow" },
  { month: 4, date: 15, name: "宇田川巴", group: "Afterglow" },
  { month: 4, date: 17, name: "宫永野乃花", group: "梦限大 MewType" },
  { month: 5, date: 6, name: "矢仓蓬咲", group: "一家 Dumb Rock!" },
  { month: 5, date: 11, name: "松原花音", group: "Hello, Happy World!" },
  { month: 5, date: 12, name: "佐藤益木(MASKING)", group: "RAISE A SUILEN" },
  { month: 5, date: 19, name: "山吹沙绫", group: "Poppin'Party" },
  { month: 5, date: 27, name: "长崎素世", group: "MyGO!!!!!" },
  { month: 6, date: 1, name: "祐天寺若麦", group: "Ave Mujica" },
  { month: 6, date: 16, name: "广町七深", group: "Morfonica" },
  { month: 6, date: 26, name: "三角初华", group: "Ave Mujica" },
  { month: 6, date: 27, name: "若宫伊芙", group: "Pastel＊Palettes" },
  { month: 7, date: 3, name: "宇田川亚子", group: "Roselia" },
  { month: 7, date: 14, name: "户山香澄", group: "Poppin'Party" },
  { month: 7, date: 16, name: "滨崎茉幌", group: "millsage" },
  { month: 7, date: 17, name: "朝日六花(LOCK)", group: "RAISE A SUILEN" },
  { month: 7, date: 28, name: "须贺蕾叶", group: "一家 Dumb Rock!" },
  { month: 7, date: 30, name: "北泽育美", group: "Hello, Happy World!" },
  { month: 8, date: 8, name: "弦卷心", group: "Hello, Happy World!" },
  { month: 8, date: 9, name: "椎名立希", group: "MyGO!!!!!" },
  { month: 8, date: 16, name: "仲町阿拉蕾", group: "梦限大 MewType" },
  { month: 8, date: 25, name: "今井莉莎", group: "Roselia" },
  { month: 9, date: 3, name: "青叶摩卡", group: "Afterglow" },
  { month: 9, date: 8, name: "千早爱音", group: "MyGO!!!!!" },
  { month: 9, date: 15, name: "二叶筑紫", group: "Morfonica" },
  { month: 9, date: 19, name: "藤都子", group: "梦限大 MewType" },
  { month: 10, date: 1, name: "奥泽美咲", group: "Hello, Happy World!" },
  { month: 10, date: 4, name: "马桥心玖", group: "一家 Dumb Rock!" },
  { month: 10, date: 17, name: "白金燐子", group: "Roselia" },
  { month: 10, date: 23, name: "上原绯玛丽", group: "Afterglow" },
  { month: 10, date: 24, name: "和泉朋花", group: "millsage" },
  { month: 10, date: 26, name: "凑友希那", group: "Roselia" },
  { month: 10, date: 27, name: "市谷有咲", group: "Poppin'Party" },
  { month: 11, date: 3, name: "大和麻弥", group: "Pastel＊Palettes" },
  { month: 11, date: 4, name: "千石由乃", group: "梦限大 MewType" },
  { month: 11, date: 19, name: "八潮瑠唯", group: "Morfonica" },
  { month: 11, date: 22, name: "高松灯", group: "MyGO!!!!!" },
  { month: 12, date: 4, name: "花园多惠", group: "Poppin'Party" },
  { month: 12, date: 7, name: "珠手知由(CHU²)", group: "RAISE A SUILEN" },
  { month: 12, date: 10, name: "琴平凪", group: "millsage" },
  { month: 12, date: 16, name: "桐谷透子", group: "Morfonica" },
  { month: 12, date: 27, name: "丸山彩", group: "Pastel＊Palettes" },
];

export const bangdream_voice_actor_birthdays = [
  { month: 1, date: 5, name: "青木阳菜", group: "MyGO!!!!!" },
  { month: 1, date: 13, name: "三泽纱千香", group: "Afterglow" },
  { month: 1, date: 13, name: "Raychell", group: "RAISE A SUILEN" },
  { month: 1, date: 22, name: "咲川日菜乃", group: "millsage" },
  { month: 1, date: 29, name: "佐仓绫音", group: "Afterglow" },
  { month: 2, date: 3, name: "小原莉子", group: "RAISE A SUILEN" },
  { month: 2, date: 8, name: "志崎桦音", group: "Roselia" },
  { month: 2, date: 15, name: "结川朝希", group: "millsage" },
  { month: 2, date: 18, name: "渡濑结月", group: "Ave Mujica" },
  { month: 2, date: 24, name: "伊驹由理惠", group: "millsage" },
  { month: 3, date: 5, name: "凉泉樱花", group: "一家 Dumb Rock!" },
  { month: 3, date: 5, name: "远野光", group: "一家 Dumb Rock!" },
  { month: 3, date: 14, name: "小日向美香", group: "MyGO!!!!!" },
  { month: 3, date: 15, name: "丰田萌绘", group: "Hello, Happy World!" },
  { month: 3, date: 16, name: "工藤晴香", group: "Roselia" },
  { month: 3, date: 26, name: "羊宫妃那", group: "MyGO!!!!!" },
  { month: 3, date: 31, name: "西尾夕香", group: "Morfonica" },
  { month: 4, date: 10, name: "千春", group: "millsage" },
  { month: 4, date: 10, name: "黑泽朋世", group: "Hello, Happy World!" },
  { month: 4, date: 17, name: "直田姬奈", group: "Morfonica" },
  { month: 4, date: 20, name: "进藤天音", group: "Morfonica" },
  { month: 5, date: 15, name: "林鼓子", group: "MyGO!!!!!" },
  { month: 5, date: 19, name: "冈田梦以", group: "Ave Mujica" },
  { month: 5, date: 19, name: "菱川花菜", group: "一家 Dumb Rock!" },
  { month: 5, date: 22, name: "仓知玲凤", group: "RAISE A SUILEN" },
  { month: 6, date: 18, name: "中上育实", group: "Pastel＊Palettes" },
  { month: 6, date: 24, name: "mika", group: "Morfonica" },
  { month: 7, date: 5, name: "纺木吏佐", group: "RAISE A SUILEN" },
  { month: 7, date: 10, name: "立石凛", group: "MyGO!!!!!" },
  { month: 7, date: 16, name: "日笠阳子", group: "Afterglow" },
  { month: 7, date: 20, name: "夏芽", group: "RAISE A SUILEN" },
  { month: 8, date: 10, name: "小泽亚李", group: "Pastel＊Palettes" },
  { month: 8, date: 17, name: "伊藤彩沙", group: "Poppin'Party" },
  { month: 8, date: 18, name: "吉田有里", group: "Hello, Happy World!" },
  { month: 9, date: 10, name: "高尾奏音", group: "Ave Mujica" },
  { month: 9, date: 11, name: "药师寺李有", group: "millsage" },
  { month: 9, date: 12, name: "中岛由贵", group: "Roselia" },
  { month: 9, date: 13, name: "大桥彩香", group: "Poppin'Party" },
  { month: 9, date: 14, name: "秦佐和子", group: "Pastel＊Palettes" },
  { month: 10, date: 10, name: "大冢纱英", group: "Poppin'Party" },
  { month: 10, date: 12, name: "伊藤美来", group: "Hello, Happy World!" },
  { month: 10, date: 17, name: "相羽爱奈", group: "Roselia" },
  { month: 10, date: 19, name: "Ayasa", group: "Morfonica" },
  { month: 10, date: 24, name: "樱川惠", group: "Roselia" },
  { month: 10, date: 24, name: "花宫初奈", group: "一家 Dumb Rock!" },
  { month: 10, date: 25, name: "西本里美", group: "Poppin'Party" },
  { month: 11, date: 10, name: "田所梓", group: "Hello, Happy World!" },
  { month: 11, date: 10, name: "佐佐木李子", group: "Ave Mujica" },
  { month: 11, date: 19, name: "橘芽衣", group: "一家 Dumb Rock!" },
  { month: 11, date: 22, name: "前岛亚美", group: "Pastel＊Palettes" },
  { month: 11, date: 26, name: "加藤英美里", group: "Afterglow" },
  { month: 12, date: 16, name: "金元寿子", group: "Afterglow" },
  { month: 12, date: 19, name: "上坂堇", group: "Pastel＊Palettes" },
  { month: 12, date: 25, name: "爱美", group: "Poppin'Party" },
  { month: 12, date: 31, name: "米泽茜", group: "Ave Mujica" },
];
